from decimal import Decimal

from shrinkflation.sizes.schema import MeasureKind

# Canonical unit name -> (measure kind, factor to base unit)
UNITS: dict[str, tuple[MeasureKind, Decimal]] = {
    "oz": (MeasureKind.WEIGHT, Decimal("28.349523125")),
    "lb": (MeasureKind.WEIGHT, Decimal("453.59237")),
    "g": (MeasureKind.WEIGHT, Decimal("1")),
    "kg": (MeasureKind.WEIGHT, Decimal("1000")),
    "mg": (MeasureKind.WEIGHT, Decimal("0.001")),
    "fl oz": (MeasureKind.VOLUME, Decimal("29.5735295625")),
    "gal": (MeasureKind.VOLUME, Decimal("3785.411784")),
    "qt": (MeasureKind.VOLUME, Decimal("946.352946")),
    "pt": (MeasureKind.VOLUME, Decimal("473.176473")),
    "cup": (MeasureKind.VOLUME, Decimal("236.5882365")),
    "l": (MeasureKind.VOLUME, Decimal("1000")),
    "ml": (MeasureKind.VOLUME, Decimal("1")),
    "count": (MeasureKind.COUNT, Decimal("1")),
    "dozen": (MeasureKind.COUNT, Decimal("12")),
    "ft": (MeasureKind.LENGTH, Decimal("0.3048")),
    "in": (MeasureKind.LENGTH, Decimal("0.0254")),
    "yd": (MeasureKind.LENGTH, Decimal("0.9144")),
    "m": (MeasureKind.LENGTH, Decimal("1")),
    "sq ft": (MeasureKind.AREA, Decimal("0.09290304")),
    "m2": (MeasureKind.AREA, Decimal("1")),
}

# Label spellings -> canonical unit. Count-like words all collapse to "count"; the specific
# word is kept in display_unit so the site still says "6 rolls".
ALIASES: dict[str, str] = {
    "oz": "oz",
    "ounce": "oz",
    "ounces": "oz",
    "onz": "oz",
    "lb": "lb",
    "lbs": "lb",
    "pound": "lb",
    "pounds": "lb",
    "g": "g",
    "gr": "g",
    "gram": "g",
    "grams": "g",
    "kg": "kg",
    "kilogram": "kg",
    "kilograms": "kg",
    "mg": "mg",
    "fl oz": "fl oz",
    "floz": "fl oz",
    "fl. oz": "fl oz",
    "fl. oz.": "fl oz",
    "fl.oz": "fl oz",
    "fluid ounce": "fl oz",
    "fluid ounces": "fl oz",
    "fl ounce": "fl oz",
    "gal": "gal",
    "gallon": "gal",
    "gallons": "gal",
    "qt": "qt",
    "quart": "qt",
    "quarts": "qt",
    "pt": "pt",
    "pint": "pt",
    "pints": "pt",
    "cup": "cup",
    "cups": "cup",
    "l": "l",
    "lt": "l",
    "ltr": "l",
    "liter": "l",
    "liters": "l",
    "litre": "l",
    "litres": "l",
    "ml": "ml",
    "milliliter": "ml",
    "milliliters": "ml",
    "millilitre": "ml",
    "ct": "count",
    "count": "count",
    "cnt": "count",
    "each": "count",
    "ea": "count",
    "pk": "count",
    "pack": "count",
    "packs": "count",
    "pc": "count",
    "pcs": "count",
    "piece": "count",
    "pieces": "count",
    "roll": "count",
    "rolls": "count",
    "sheet": "count",
    "sheets": "count",
    "bag": "count",
    "bags": "count",
    "bar": "count",
    "bars": "count",
    "can": "count",
    "cans": "count",
    "bottle": "count",
    "bottles": "count",
    "pod": "count",
    "pods": "count",
    "tablet": "count",
    "tablets": "count",
    "capsule": "count",
    "capsules": "count",
    "caplet": "count",
    "caplets": "count",
    "softgel": "count",
    "softgels": "count",
    "gummy": "count",
    "gummies": "count",
    "stick": "count",
    "sticks": "count",
    "cup(s)": "count",
    "unit": "count",
    "units": "count",
    "load": "count",
    "loads": "count",
    "pouch": "count",
    "pouches": "count",
    "packet": "count",
    "packets": "count",
    "tea bags": "count",
    "k-cups": "count",
    "kcups": "count",
    "wipes": "count",
    "diapers": "count",
    "servings": "count",
    "serving": "count",
    "dozen": "dozen",
    "dz": "dozen",
    "doz": "dozen",
    "ft": "ft",
    "feet": "ft",
    "foot": "ft",
    "in": "in",
    "inch": "in",
    "inches": "in",
    "yd": "yd",
    "yard": "yd",
    "yards": "yd",
    "m": "m",
    "meter": "m",
    "meters": "m",
    "sq ft": "sq ft",
    "sqft": "sq ft",
    "sq. ft.": "sq ft",
    "square feet": "sq ft",
    "square foot": "sq ft",
}


def canonical_unit(label: str) -> str | None:
    key = " ".join(label.lower().replace(".", ". ").split()).replace(" .", ".").strip(" .")
    key = key.replace(". ", ".").replace(".", ". ").strip()
    key = " ".join(key.split())
    if key in ALIASES:
        return ALIASES[key]
    compact = key.replace(". ", "").replace(" ", "").replace(".", "")
    for alias, canon in ALIASES.items():
        if alias.replace(".", "").replace(" ", "") == compact:
            return canon
    return None
