/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Changes */
        get: operations["changes_api_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products */
        get: operations["products_api_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product Detail */
        get: operations["product_detail_api_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories */
        get: operations["categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ask Budget */
        get: operations["ask_budget_api_ask_budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCallOut"][];
            /** Model */
            model: string;
            /** Total Tokens */
            total_tokens: number;
            /** Latency Ms */
            latency_ms: number;
            /** Questions Remaining */
            questions_remaining: number;
            /** Trace Id */
            trace_id?: string | null;
        };
        /** BudgetOut */
        BudgetOut: {
            /** Questions Per Day */
            questions_per_day: number;
            /** Questions Remaining */
            questions_remaining: number;
        };
        /** CategoryCount */
        CategoryCount: {
            /** Category */
            category: string;
            /** Products */
            products: number;
            /** Changes */
            changes: number;
        };
        /** ChangeList */
        ChangeList: {
            /** Items */
            items: components["schemas"]["ChangeOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ChangeOut */
        ChangeOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Source */
            source: string;
            product: components["schemas"]["ProductSummary"];
            before?: components["schemas"]["SnapshotOut"] | null;
            after?: components["schemas"]["SnapshotOut"] | null;
            /** Size Change Pct */
            size_change_pct?: string | null;
            /** Price Change Pct */
            price_change_pct?: string | null;
            /** Unit Price Change Pct */
            unit_price_change_pct?: string | null;
            /** Before Seen At */
            before_seen_at?: string | null;
            /** After Seen At */
            after_seen_at?: string | null;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Note */
            note?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Last Run Finished At */
            last_run_finished_at?: string | null;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /** LastRun */
        LastRun: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Products Checked */
            products_checked: number;
            /** Snapshots Added */
            snapshots_added: number;
            /** Changes Found */
            changes_found: number;
            /** Api Calls */
            api_calls: number;
            /** Errors */
            errors: number;
        };
        /** ProductDetail */
        ProductDetail: {
            product: components["schemas"]["ProductSummary"];
            /** Upc */
            upc?: string | null;
            /** Retailer Categories */
            retailer_categories?: string[];
            /** Active */
            active: boolean;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            current?: components["schemas"]["SnapshotOut"] | null;
            /** Snapshots */
            snapshots: components["schemas"]["SnapshotOut"][];
            /** Changes */
            changes: components["schemas"]["ChangeOut"][];
        };
        /** ProductSearchResult */
        ProductSearchResult: {
            /** Items */
            items: components["schemas"]["ProductSummary"][];
        };
        /** ProductSummary */
        ProductSummary: {
            /** Id */
            id: string;
            /** Description */
            description: string;
            /** Brand */
            brand?: string | null;
            /** Category */
            category: string;
            /** Image Url */
            image_url?: string | null;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /** Id */
            id: number;
            /** Size Text */
            size_text: string;
            /** Display Quantity */
            display_quantity?: string | null;
            /** Display Unit */
            display_unit?: string | null;
            /** Quantity */
            quantity?: string | null;
            /** Base Unit */
            base_unit?: string | null;
            /** Price Regular */
            price_regular?: string | null;
            /** Price Promo */
            price_promo?: string | null;
            unit_price?: components["schemas"]["UnitPrice"] | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Observations */
            observations: number;
            /** Parse Method */
            parse_method?: string | null;
            /** Parse Confidence */
            parse_confidence?: number | null;
        };
        /** Stats */
        Stats: {
            /** Products Tracked */
            products_tracked: number;
            /** Categories */
            categories: number;
            /** Snapshots */
            snapshots: number;
            /** Changes Published */
            changes_published: number;
            /** Shrink Count */
            shrink_count: number;
            /** Grow Count */
            grow_count: number;
            /** Price Increase Count */
            price_increase_count: number;
            /** Llm Calls */
            llm_calls: number;
            /** Llm Cost Usd */
            llm_cost_usd: string;
            /** Tracking Since */
            tracking_since?: string | null;
            last_run?: components["schemas"]["LastRun"] | null;
            /** Location Label */
            location_label: string;
        };
        /** ToolCallOut */
        ToolCallOut: {
            /** Name */
            name: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Ms */
            ms: number;
            /** Ok */
            ok: boolean;
        };
        /** UnitPrice */
        UnitPrice: {
            /**
             * Value
             * @description Price per display unit, in dollars
             */
            value: string;
            /**
             * Unit
             * @description Unit the price is per, for example oz, fl oz, each
             */
            unit: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    changes_api_changes_get: {
        parameters: {
            query?: {
                kind?: string;
                category?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    products_api_products_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_detail_api_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryCount"][];
                };
            };
        };
    };
    ask_budget_api_ask_budget_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOut"];
                };
            };
        };
    };
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
