"""initial schema

Revision ID: 55cf162006c9
Revises:
Create Date: 2026-09-07 17:34:31.620211
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "55cf162006c9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ask_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("visitor_key", sa.String(length=64), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ask_log_created_at"), "ask_log", ["created_at"], unique=False)
    op.create_index(op.f("ix_ask_log_visitor_key"), "ask_log", ["visitor_key"], unique=False)
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("products_checked", sa.Integer(), nullable=False),
        sa.Column("snapshots_added", sa.Integer(), nullable=False),
        sa.Column("changes_found", sa.Integer(), nullable=False),
        sa.Column("api_calls", sa.Integer(), nullable=False),
        sa.Column("llm_calls", sa.Integer(), nullable=False),
        sa.Column("llm_cost_usd", sa.Numeric(precision=10, scale=5), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column("error_sample", sa.Text(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("upc", sa.String(length=32), nullable=True),
        sa.Column("brand", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("retailer_categories", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("search_terms", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_active"), "products", ["active"], unique=False)
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    op.create_index(op.f("ix_products_upc"), "products", ["upc"], unique=False)
    op.create_table(
        "size_parses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("size_text", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("measure_kind", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("base_unit", sa.String(length=8), nullable=True),
        sa.Column("display_quantity", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("display_unit", sa.String(length=16), nullable=True),
        sa.Column("pack_count", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ux_size_parses_text_desc", "size_parses", ["size_text", "description"], unique=True
    )
    op.create_table(
        "visitor_budgets",
        sa.Column("visitor_key", sa.String(length=64), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("questions_used", sa.Integer(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("visitor_key", "day"),
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column("span_id", sa.String(length=16), nullable=True),
        sa.Column("pipeline_run_id", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_calls_created_at"), "llm_calls", ["created_at"], unique=False)
    op.create_index(op.f("ix_llm_calls_purpose"), "llm_calls", ["purpose"], unique=False)
    op.create_index(op.f("ix_llm_calls_trace_id"), "llm_calls", ["trace_id"], unique=False)
    op.create_table(
        "snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.String(length=32), nullable=False),
        sa.Column("location_id", sa.String(length=16), nullable=False),
        sa.Column("size_text", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("sold_by", sa.String(length=16), nullable=True),
        sa.Column("price_regular", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("price_promo", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("size_parse_id", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observations", sa.Integer(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["size_parse_id"],
            ["size_parses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_snapshots_product_id"), "snapshots", ["product_id"], unique=False)
    op.create_index(
        "ix_snapshots_product_last_seen", "snapshots", ["product_id", "last_seen_at"], unique=False
    )
    op.create_index(
        op.f("ix_snapshots_size_parse_id"), "snapshots", ["size_parse_id"], unique=False
    )
    op.create_table(
        "changes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("before_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("after_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("base_unit", sa.String(length=8), nullable=True),
        sa.Column("before_quantity", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("after_quantity", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("before_size_text", sa.String(length=120), nullable=True),
        sa.Column("after_size_text", sa.String(length=120), nullable=True),
        sa.Column("before_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("after_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("size_change_pct", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("price_change_pct", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("unit_price_change_pct", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("before_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("after_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["after_snapshot_id"],
            ["snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["before_snapshot_id"],
            ["snapshots.id"],
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_changes_detected_at"), "changes", ["detected_at"], unique=False)
    op.create_index(op.f("ix_changes_kind"), "changes", ["kind"], unique=False)
    op.create_index(op.f("ix_changes_product_id"), "changes", ["product_id"], unique=False)
    op.create_index(op.f("ix_changes_status"), "changes", ["status"], unique=False)
    op.create_index(
        "ux_changes_transition",
        "changes",
        ["product_id", "before_snapshot_id", "after_snapshot_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ux_changes_transition", table_name="changes")
    op.drop_index(op.f("ix_changes_status"), table_name="changes")
    op.drop_index(op.f("ix_changes_product_id"), table_name="changes")
    op.drop_index(op.f("ix_changes_kind"), table_name="changes")
    op.drop_index(op.f("ix_changes_detected_at"), table_name="changes")
    op.drop_table("changes")
    op.drop_index(op.f("ix_snapshots_size_parse_id"), table_name="snapshots")
    op.drop_index("ix_snapshots_product_last_seen", table_name="snapshots")
    op.drop_index(op.f("ix_snapshots_product_id"), table_name="snapshots")
    op.drop_table("snapshots")
    op.drop_index(op.f("ix_llm_calls_trace_id"), table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_purpose"), table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_created_at"), table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_table("visitor_budgets")
    op.drop_index("ux_size_parses_text_desc", table_name="size_parses")
    op.drop_table("size_parses")
    op.drop_index(op.f("ix_products_upc"), table_name="products")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_index(op.f("ix_products_active"), table_name="products")
    op.drop_table("products")
    op.drop_table("pipeline_runs")
    op.drop_index(op.f("ix_ask_log_visitor_key"), table_name="ask_log")
    op.drop_index(op.f("ix_ask_log_created_at"), table_name="ask_log")
    op.drop_table("ask_log")
    # ### end Alembic commands ###
